"""add picture_upload to inventory_items and picture_path to order_inventory_data

Revision ID: 2434ff7a999b
Revises: 41b0ba1bad82
Create Date: 2025-11-06 10:46:47.382369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2434ff7a999b'
down_revision: Union[str, Sequence[str], None] = '41b0ba1bad82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('picture_upload', sa.Boolean(), nullable=False, server_default='false'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('inventory_items', 'picture_upload')
    # ### end Alembic commands ###
