"""Standardize to singular bodywork

Revision ID: 26e16ad10bbd
Revises: 65eed46722f5
Create Date: 2025-10-20 16:03:23.915372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26e16ad10bbd'
down_revision: Union[str, Sequence[str], None] = '65eed46722f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Renombrar la tabla de 'bodywork_checklist' a 'bodywork_details'
    op.rename_table('bodywork_checklist', 'bodywork_details')
    # 2. Renombrar la columna de 'checklist_id' a 'detail_id'
    op.alter_column('bodywork_details', 'checklist_id', new_column_name='detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir los cambios en orden inverso
    op.alter_column('bodywork_details', 'detail_id', new_column_name='checklist_id')
    op.rename_table('bodywork_details', 'bodywork_checklist')
    # ### end Alembic commands ###
