"""Update tables

Revision ID: 318af7f044b0
Revises: 79e40d90886a
Create Date: 2025-09-26 13:28:12.134309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318af7f044b0'
down_revision: Union[str, Sequence[str], None] = '79e40d90886a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_extra_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('order_extra_info',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['order_extra_items.item_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'item_id')
    )
    op.add_column('orders', sa.Column('has_extra_info', sa.Boolean(), nullable=True))
    op.drop_column('vehicles', 'fleet_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fleet_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'has_extra_info')
    op.drop_table('order_extra_info')
    op.drop_table('order_extra_items')
    # ### end Alembic commands ###
