"""rename_value_to_data_in_orderinventorydata

Revision ID: 39beb96209c7
Revises: 2434ff7a999b
Create Date: 2025-11-06 12:34:37.972470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39beb96209c7'
down_revision: Union[str, Sequence[str], None] = '2434ff7a999b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_inventory_data', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('order_inventory_data', sa.Column('is_mandatory', sa.Boolean(), nullable=False))
    op.alter_column('order_inventory_data', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('_order_inventory_type_uc'), 'order_inventory_data', type_='unique')
    op.create_unique_constraint('_order_item_uc', 'order_inventory_data', ['order_id', 'item_id'])
    op.create_index(op.f('ix_order_inventory_data_item_id'), 'order_inventory_data', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_inventory_data_order_id'), 'order_inventory_data', ['order_id'], unique=False)
    op.drop_constraint(op.f('order_inventory_data_inv_type_id_fkey'), 'order_inventory_data', type_='foreignkey')
    op.create_foreign_key(None, 'order_inventory_data', 'inventory_items', ['item_id'], ['item_id'], ondelete='CASCADE')
    op.drop_column('order_inventory_data', 'inv_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_inventory_data', sa.Column('inv_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_inventory_data', type_='foreignkey')
    op.create_foreign_key(op.f('order_inventory_data_inv_type_id_fkey'), 'order_inventory_data', 'inventory_types', ['inv_type_id'], ['inv_type_id'])
    op.drop_index(op.f('ix_order_inventory_data_order_id'), table_name='order_inventory_data')
    op.drop_index(op.f('ix_order_inventory_data_item_id'), table_name='order_inventory_data')
    op.drop_constraint('_order_item_uc', 'order_inventory_data', type_='unique')
    op.create_unique_constraint(op.f('_order_inventory_type_uc'), 'order_inventory_data', ['order_id', 'inv_type_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('order_inventory_data', 'data',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('order_inventory_data', 'is_mandatory')
    op.drop_column('order_inventory_data', 'item_id')
    # ### end Alembic commands ###
