"""detail type id nullable for new details

Revision ID: 3f23d68057b5
Revises: 26e16ad10bbd
Create Date: 2025-10-24 12:38:16.653156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23d68057b5'
down_revision: Union[str, Sequence[str], None] = '26e16ad10bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bodywork_details', 'detail_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bodywork_details', 'detail_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
