"""Add inventory tables and relationships

Revision ID: 41b0ba1bad82
Revises: 4d20d6ca3a37
Create Date: 2025-11-04 11:33:07.507030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41b0ba1bad82'
down_revision: Union[str, Sequence[str], None] = '4d20d6ca3a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_types',
    sa.Column('inv_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_key', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('picture_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('inv_type_id')
    )
    op.create_table('inventory_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('inv_type_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('input_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inv_type_id'], ['inventory_types.inv_type_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('order_inventory_data',
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('inv_type_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['inv_type_id'], ['inventory_types.inv_type_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('order_id', 'inv_type_id', name='_order_inventory_type_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_inventory_data')
    op.drop_table('inventory_items')
    op.drop_table('inventory_types')
    # ### end Alembic commands ###
