"""Appointments added

Revision ID: 457daba65407
Revises: 6b4d81719f21
Create Date: 2025-11-13 12:15:39.267776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457daba65407'
down_revision: Union[str, Sequence[str], None] = '6b4d81719f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_reasons',
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('reason_id'),
    sa.UniqueConstraint('reason')
    )
    op.create_table('appointment_status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('rescheduled_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reason_id'], ['appointment_reasons.reason_id'], ),
    sa.ForeignKeyConstraint(['scheduled_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['appointment_status.status_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('appointment_status')
    op.drop_table('appointment_reasons')
    # ### end Alembic commands ###
