"""Remove is_free_selection from bodywork_details

Revision ID: 4d20d6ca3a37
Revises: d189e9af6416
Create Date: 2025-11-03 13:33:02.708635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d20d6ca3a37'
down_revision: Union[str, Sequence[str], None] = 'd189e9af6416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodywork_details', 'is_free_selection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodywork_details', sa.Column('is_free_selection', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
