"""appointments temp fields added

Revision ID: 4efa3d3be656
Revises: 457daba65407
Create Date: 2025-11-14 14:40:55.935356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4efa3d3be656'
down_revision: Union[str, Sequence[str], None] = '457daba65407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('temp_cname', sa.String(length=64), nullable=True))
    op.add_column('appointments', sa.Column('temp_fname', sa.String(length=64), nullable=True))
    op.add_column('appointments', sa.Column('temp_lname', sa.String(length=64), nullable=True))
    op.add_column('appointments', sa.Column('temp_email', sa.String(length=128), nullable=True))
    op.add_column('appointments', sa.Column('temp_phone', sa.String(length=32), nullable=True))
    op.add_column('appointments', sa.Column('temp_vehicle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'temp_vehicle_data')
    op.drop_column('appointments', 'temp_phone')
    op.drop_column('appointments', 'temp_email')
    op.drop_column('appointments', 'temp_lname')
    op.drop_column('appointments', 'temp_fname')
    op.drop_column('appointments', 'temp_cname')
    # ### end Alembic commands ###
