"""Color column added to  detail type  table

Revision ID: 636d6e92b48e
Revises: 978f90971315
Create Date: 2025-10-20 15:08:06.658353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636d6e92b48e'
down_revision: Union[str, Sequence[str], None] = '978f90971315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodywork_detail_types', sa.Column('color', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodywork_detail_types', 'color')
    # ### end Alembic commands ###
