"""convert_order_inventory_data_to_jsonb_preserving_data

Revision ID: 6b4d81719f21
Revises: f3df742102ee
Create Date: 2025-11-10 10:42:12.005441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6b4d81719f21'
down_revision: Union[str, Sequence[str], None] = 'f3df742102ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convierte la columna 'data' de String a JSONB,
    # envolviendo el valor de texto existente en un objeto JSON.
    op.alter_column('order_inventory_data', 'data',
               existing_type=sa.String(), # Tipo existente: String (VARCHAR)
               type_=postgresql.JSONB(astext_type=sa.Text()), # Nuevo tipo: JSONB
               postgresql_using="jsonb_build_object('value', data)", # Cómo convertir los datos
               nullable=True) # Mantener la nulabilidad deseada
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convierte la columna 'data' de JSONB de nuevo a String,
    # extrayendo el valor del objeto JSON.
    op.alter_column('order_inventory_data', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()), # Tipo existente: JSONB
               type_=sa.String(), # Nuevo tipo: String (VARCHAR)
               postgresql_using="data->>'value'", # Cómo extraer los datos
               nullable=True) # Mantener la nulabilidad consistente
    # ### end Alembic commands ###
