"""Update tables

Revision ID: 79e40d90886a
Revises: 6c68e9cf6b15
Create Date: 2025-09-25 15:41:24.003931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e40d90886a'
down_revision: Union[str, Sequence[str], None] = '6c68e9cf6b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('make_id'),
    sa.UniqueConstraint('make')
    )
    op.create_table('transmissions',
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('transmission_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['makes.make_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.add_column('vehicles', sa.Column('model_id', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('transmission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vehicles', 'transmissions', ['transmission_id'], ['transmission_id'])
    op.create_foreign_key(None, 'vehicles', 'models', ['model_id'], ['model_id'])
    op.drop_column('vehicles', 'make')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'transmission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('transmission', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('make', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'transmission_id')
    op.drop_column('vehicles', 'model_id')
    op.drop_table('models')
    op.drop_table('transmissions')
    op.drop_table('makes')
    # ### end Alembic commands ###
