"""Create all tables

Revision ID: 894e77d8fdbf
Revises: 
Create Date: 2025-09-24 15:52:58.454031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894e77d8fdbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_status',
    sa.Column('adm_status_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('adm_status_id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('colors',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('color_id'),
    sa.UniqueConstraint('color')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('cname', sa.String(length=64), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('motors',
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('motor_id')
    )
    op.create_table('op_status',
    sa.Column('op_status_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('op_status_id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('priority',
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('priority_id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_employee', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle_types',
    sa.Column('v_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('v_type_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=False),
    sa.Column('lname1', sa.String(length=64), nullable=False),
    sa.Column('lname2', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('plate', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fleet_number', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.String(length=32), nullable=False),
    sa.Column('cylinders', sa.Integer(), nullable=False),
    sa.Column('liters', sa.String(length=16), nullable=False),
    sa.Column('v_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.color_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.motor_id'], ),
    sa.ForeignKeyConstraint(['v_type_id'], ['vehicle_types.v_type_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('c_order_id', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('op_status_id', sa.Integer(), nullable=True),
    sa.Column('adm_status_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('p_mileage', sa.Integer(), nullable=True),
    sa.Column('c_mileage', sa.Integer(), nullable=True),
    sa.Column('service_bay', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['adm_status_id'], ['adm_status.adm_status_id'], ),
    sa.ForeignKeyConstraint(['advisor_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['op_status_id'], ['op_status.op_status_id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priority.priority_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('c_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('vehicles')
    op.drop_table('user_permissions')
    op.drop_table('employees')
    op.drop_table('contacts')
    op.drop_table('vehicle_types')
    op.drop_table('users')
    op.drop_table('priority')
    op.drop_table('positions')
    op.drop_table('permissions')
    op.drop_table('op_status')
    op.drop_table('motors')
    op.drop_table('customers')
    op.drop_table('colors')
    op.drop_table('adm_status')
    # ### end Alembic commands ###
