"""add_multitenancy_and_auth_fields

Revision ID: 8ad84d1c95ba
Revises: b2ebd33e901a
Create Date: 2026-06-09 08:56:06.258995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad84d1c95ba'
down_revision: Union[str, Sequence[str], None] = 'b2ebd33e901a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['employee_id'], ondelete='SET NULL')
    op.add_column('vehicles', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'supabase_uid')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'company_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'company_id')
    # ### end Alembic commands ###
