"""Add Bodywork checklist tables

Revision ID: 978f90971315
Revises: f3a350c526d0
Create Date: 2025-10-20 14:52:50.641851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978f90971315'
down_revision: Union[str, Sequence[str], None] = 'f3a350c526d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodywork_detail_types',
    sa.Column('detail_type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('detail_type_id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('bodywork_checklist',
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('detail_type_id', sa.Integer(), nullable=False),
    sa.Column('detail_notes', sa.String(length=256), nullable=True),
    sa.Column('picture_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['detail_type_id'], ['bodywork_detail_types.detail_type_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checklist_id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bodywork_checklist')
    op.drop_table('bodywork_detail_types')
    # ### end Alembic commands ###
