"""add_companies_and_whatsapp_models

Revision ID: b2ebd33e901a
Revises: 0829815eb5d3
Create Date: 2026-06-08 12:27:31.218357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ebd33e901a'
down_revision: Union[str, Sequence[str], None] = '0829815eb5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('whatsapp_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('phone_number_id')
    )
    op.create_table('whatsapp_conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('company_id', 'customer_phone', name='_company_customer_phone_uc')
    )
    op.create_table('whatsapp_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('body', sa.String(length=1024), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_table('whatsapp_messages')
    op.drop_table('whatsapp_conversations')
    op.drop_table('whatsapp_configs')
    op.drop_table('companies')
    # ### end Alembic commands ###
