"""add cancellation fields to appointments

Revision ID: bb5895b3e104
Revises: ff203d052527
Create Date: 2026-09-25 17:26:57.038034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5895b3e104'
down_revision: Union[str, Sequence[str], None] = 'ff203d052527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancellation_reason', sa.String(length=256), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancellation_date')
    op.drop_column('appointments', 'cancellation_reason')
    # ### end Alembic commands ###
