"""Replace bodywork x,y with coordinates JSONB

Revision ID: d189e9af6416
Revises: 3f23d68057b5
Create Date: 2025-11-03 13:16:21.922003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd189e9af6416'
down_revision: Union[str, Sequence[str], None] = '3f23d68057b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodywork_details', sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('bodywork_details', 'x')
    op.drop_column('bodywork_details', 'y')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodywork_details', sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bodywork_details', sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('bodywork_details', 'coordinates')
    # ### end Alembic commands ###
