"""add appointment settings fields to company_settings

Revision ID: d205a92f2c8e
Revises: bb5895b3e104
Create Date: 2026-09-26 13:59:56.976892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd205a92f2c8e'
down_revision: Union[str, Sequence[str], None] = 'bb5895b3e104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('appointment_start_time', sa.Time(), nullable=True))
    op.add_column('company_settings', sa.Column('appointment_end_time', sa.Time(), nullable=True))
    op.add_column('company_settings', sa.Column('slot_duration_minutes', sa.Integer(), server_default='30', nullable=True))
    op.add_column('company_settings', sa.Column('allowed_days', postgresql.JSONB(astext_type=sa.Text()), server_default='[0, 1, 2, 3, 4, 5]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'allowed_days')
    op.drop_column('company_settings', 'slot_duration_minutes')
    op.drop_column('company_settings', 'appointment_end_time')
    op.drop_column('company_settings', 'appointment_start_time')
    # ### end Alembic commands ###
