"""fuel_level added to orders table

Revision ID: f3a350c526d0
Revises: 318af7f044b0
Create Date: 2025-10-09 16:18:32.754806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a350c526d0'
down_revision: Union[str, Sequence[str], None] = '318af7f044b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fuel_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'fuel_level')
    # ### end Alembic commands ###
