"""refactor_order_inventory_data_and_move_is_mandatory

Revision ID: f3df742102ee
Revises: 39beb96209c7
Create Date: 2025-11-06 12:44:08.039855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3df742102ee'
down_revision: Union[str, Sequence[str], None] = '39beb96209c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('order_inventory_data', 'is_mandatory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_inventory_data', sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('inventory_items', 'is_mandatory')
    # ### end Alembic commands ###
