"""add company_id to inventory tables

Revision ID: ff203d052527
Revises: 8ad84d1c95ba
Create Date: 2026-07-02 23:36:49.584565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff203d052527'
down_revision: Union[str, Sequence[str], None] = '8ad84d1c95ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_items', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.add_column('inventory_types', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_types', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # --- Data Migration ---
    # 1. Asignar los inventarios y elementos existentes a la empresa 1 (Taller de Pruebas)
    op.execute("UPDATE inventory_types SET company_id = 1")
    op.execute("UPDATE inventory_items SET company_id = 1")

    # 2. Crear el registro de plantilla maestra global (company_id = NULL) copiando del de carrocería (ID 1)
    op.execute(
        "INSERT INTO inventory_types (name, component_key, is_active, position, picture_path, company_id) "
        "SELECT name, component_key, is_active, position, picture_path, NULL FROM inventory_types WHERE inv_type_id = 1"
    )
    op.execute(
        "INSERT INTO inventory_items (inv_type_id, label, input_type, position, description, picture_upload, is_mandatory, company_id) "
        "SELECT (SELECT inv_type_id FROM inventory_types WHERE company_id IS NULL AND name = 'carroceria' LIMIT 1), "
        "label, input_type, position, description, picture_upload, is_mandatory, NULL "
        "FROM inventory_items WHERE inv_type_id = 1"
    )

    # 3. Clonar la plantilla maestra para la empresa 2 (Taller Local Test)
    op.execute(
        "INSERT INTO inventory_types (name, component_key, is_active, position, picture_path, company_id) "
        "SELECT name, component_key, is_active, position, picture_path, 2 FROM inventory_types WHERE inv_type_id = 1"
    )
    op.execute(
        "INSERT INTO inventory_items (inv_type_id, label, input_type, position, description, picture_upload, is_mandatory, company_id) "
        "SELECT (SELECT inv_type_id FROM inventory_types WHERE company_id = 2 AND name = 'carroceria' LIMIT 1), "
        "label, input_type, position, description, picture_upload, is_mandatory, 2 "
        "FROM inventory_items WHERE inv_type_id = 1"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Eliminar datos clonados creados durante la migración
    op.execute("DELETE FROM inventory_items WHERE company_id IS NULL OR company_id = 2")
    op.execute("DELETE FROM inventory_types WHERE company_id IS NULL OR company_id = 2")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_types', type_='foreignkey')
    op.drop_column('inventory_types', 'company_id')
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'company_id')
    # ### end Alembic commands ###
